<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoFixture" Version="4.18.1" />
		<PackageReference Include="EPiServer.CMS" Version="12.32.5" />
		<PackageReference Include="EPiServer.CMS.AspNetCore" Version="12.22.5" />
		<PackageReference Include="EPiServer.CMS.AspNetCore.HtmlHelpers" Version="12.22.5" />
		<PackageReference Include="EPiServer.CMS.AspNetCore.TagHelpers" Version="12.22.5" />
		<PackageReference Include="EPiServer.CMS.AspNetCore.Templating" Version="12.22.5" />
		<PackageReference Include="EPiServer.CMS.AspNetCore.Routing" Version="12.22.5" />
		<PackageReference Include="EPiServer.CMS.Core" Version="12.22.5" />
		<PackageReference Include="EPiServer.CMS.TinyMce" Version="5.0.0" />
		<PackageReference Include="EPiServer.CMS.UI.Core" Version="12.32.5" />
		<PackageReference Include="EPiServer.Hosting" Version="12.22.5" />
		<PackageReference Include="EPiServer.Framework" Version="12.22.5" />
		<PackageReference Include="Geta.Optimizely.ContentTypeIcons" Version="2.0.2" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
		<PackageReference Include="Moq" Version="4.17.2" />
		<PackageReference Include="NUnit" Version="4.3.2" />
		<PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
		<PackageReference Include="NUnit.Analyzers" Version="4.6.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="coverlet.collector" Version="6.0.3">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="System.Linq.Async" Version="6.0.1" />
		<PackageReference Include="EPiServer.CloudPlatform.Cms" Version="1.6.3" />

	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Salam.Cms.Web\Salam.Cms.Web.csproj" />
		<ProjectReference Include="..\Salam.Cms.Web.Infrastructure\Salam.Cms.Web.Infrastructure.csproj" />
		<ProjectReference Include="..\Salam.Cms.Shared.Models\Salam.Cms.Shared.Models.csproj" />
		<ProjectReference Include="..\Salam.Cms.Core.Services\Salam.Cms.Core.Services.csproj" />
		<ProjectReference Include="..\Salam.Cms.Core.Settings\Salam.Cms.Core.Settings.csproj" />
	</ItemGroup>

</Project>
