<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	  <Optimize>True</Optimize>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	  <Optimize>False</Optimize>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Advanced.CMS.AdvancedReviews" Version="1.3.10" />
		<PackageReference Include="EPiServer.Cms.WelcomeIntegration.Graph" Version="2.1.4" />
		<PackageReference Include="EPiServer.Cms.WelcomeIntegration.UI" Version="2.1.4" />
		<PackageReference Include="EPiServer.Labs.LanguageManager" Version="5.5.0" />
		<PackageReference Include="EPiServer.OptimizelyIdentity" Version="1.0.4" />
		<PackageReference Include="Flurl" Version="4.0.0" />
		<PackageReference Include="Flurl.Http" Version="4.0.2" />
		<PackageReference Include="Google.Apis.Auth" Version="1.72.0" />
		<PackageReference Include="Google.Apis.RecaptchaEnterprise.v1" Version="1.72.0.3931" />
		<PackageReference Include="Google.Cloud.RecaptchaEnterprise.V1" Version="2.18.0" />
		<PackageReference Include="Grpc.Auth" Version="2.66.0" />
		<PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="8.6.1" />
		<PackageReference Include="NaturalSort.Extension" Version="4.3.0" />
		<PackageReference Include="Optimizely.Cms.Cmp.Publishing" Version="1.3.0" />
		<!--<PackageReference Include="Salam.Presentation.UI" Version="1.1.3" />-->
		<PackageReference Include="Serilog" Version="2.12.0" />
		<PackageReference Include="Serilog.AspNetCore" Version="6.1.0" />
		<PackageReference Include="Serilog.Formatting.Compact" Version="1.1.1-dev-00944" />
		<PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
		<PackageReference Include="EPiServer.Forms.UI" Version="5.10.2" />
		<PackageReference Include="EPiServer.Forms" Version="5.10.2" />
		<PackageReference Include="EPiServer.CloudPlatform.Cms" Version="1.6.3" />
		<PackageReference Include="EPiServer.CMS" Version="12.32.5" />
		<PackageReference Include="EPiServer.Azure" Version="11.2.1" />
		<PackageReference Include="EPiServer.CMS.AspNetCore.HtmlHelpers" Version="12.22.5" />
		<PackageReference Include="EPiServer.CMS.AspNetCore.TagHelpers" Version="12.22.5" />
		<PackageReference Include="EPiServer.CMS.AspNetCore.Templating" Version="12.22.5" />
		<PackageReference Include="EPiServer.CMS.AspNetCore.Routing" Version="12.22.5" />
		<PackageReference Include="EPiServer.CMS.TinyMce" Version="5.0.0" />
		<PackageReference Include="EPiServer.CMS.UI.Core" Version="12.32.5" />
		<PackageReference Include="EPiServer.ContentDeliveryApi.Cms" Version="3.11.3" />
		<PackageReference Include="EPiServer.Find.Cms" Version="16.5.0" />
		<PackageReference Include="EPiServer.Hosting" Version="12.22.5" />
		<PackageReference Include="Geta.NotFoundHandler.Optimizely" Version="5.0.13" />
		<PackageReference Include="Geta.Optimizely.Categories" Version="1.1.2" />
		<PackageReference Include="Geta.Optimizely.ContentTypeIcons" Version="2.0.2" />
		<PackageReference Include="Geta.Optimizely.Sitemaps" Version="3.1.2" />
		<PackageReference Include="ImagePointEditor" Version="2.2.0" />
		<PackageReference Include="OpenIddict.Server" Version="6.0.0" />
		<PackageReference Include="PictureRenderer.Optimizely" Version="3.2.0" />
		<PackageReference Include="Stott.Optimizely.RobotsHandler" Version="5.0.0" />
		<PackageReference Include="Stott.Security.Optimizely" Version="3.0.2" />
		<PackageReference Include="Optimizely.Cms.Forms.Service" Version="1.0.0" />
		<PackageReference Include="Optimizely.ContentGraph.Cms" Version="3.14.3" />
		<PackageReference Include="System.Linq.Async" Version="6.0.1" />
		<PackageReference Include="UNRVLD.ODP.VisitorGroups" Version="2.1.0.59" />
		<PackageReference Include="Verndale.RedirectManager" Version="3.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Salam.Cms.Plugin.ApiExplorer\Salam.Cms.Plugin.ApiExplorer.csproj" />
		<ProjectReference Include="..\Salam.Cms.Web.Infrastructure\Salam.Cms.Web.Infrastructure.csproj" />
		<ProjectReference Include="..\Salam.Cms.Web.Features\Salam.Cms.Web.Features.csproj" />
		<ProjectReference Include="..\Salam.Cms.Shared.Models\Salam.Cms.Shared.Models.csproj" />
		<ProjectReference Include="..\Salam.Cms.Core.Services\Salam.Cms.Core.Services.csproj" />
		<ProjectReference Include="..\Salam.Cms.Core.Settings\Salam.Cms.Core.Settings.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Resources\AdvancedReviews\*.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
	  <Compile Remove="API\Services\**" />
	  <Content Remove="API\Services\**" />
	  <EmbeddedResource Remove="API\Services\**" />
	  <None Remove="API\Services\**" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="Views\Shared\Partials\ProductSelector\Common\Unlimited.cshtml" />
	  <None Include="wwwroot\static\assets\js\LanguageChangeEventDispatcher.js" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Views\Shared\Components\B2BInfrastructureCardBlock\" />
	</ItemGroup>
</Project>
